In [1]:
import context
import libs.quaternion_operations as quat_op
import quaternion as quat
import numpy as np


In [2]:
def q2ea(q):
    if type(q) == 'quaternion':
        q = [q.x, q.y, q.z, q.w]
    ea = quat_op.Q2EA((q[3], q[0], q[1], q[2]), EulerOrder="zyx", ignoreAllChk=True)[0]

    return np.array(ea)/np.pi*180

In [3]:
x = np.array([0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

xs = np.array([0.0, 0.1, 0.5, 0.9, 1.0])
ys = np.array([0.0, 0.1, 0.5, 0.9, 1.0])
zs = np.array([0.0, 0.1, 0.5, 0.9, 1.0])
ws = np.array([0.0, 0.1, 0.5, 0.9, 1.0])


for x in xs:
    for y in ys:
        for z in zs:
            for w in ws:
                q = [x,y,z,w]
                print(q)
                print(q2ea(q))
                print('')

[0.0, 0.0, 0.0, 0.0]
[nan nan nan]

[0.0, 0.0, 0.0, 0.1]
[0. 0. 0.]

[0.0, 0.0, 0.0, 0.5]
[0. 0. 0.]

[0.0, 0.0, 0.0, 0.9]
[0. 0. 0.]

[0.0, 0.0, 0.0, 1.0]
[0. 0. 0.]

[0.0, 0.0, 0.1, 0.0]
[  0.   0. 180.]

[0.0, 0.0, 0.1, 0.1]
[ 0.  0. 90.]

[0.0, 0.0, 0.1, 0.5]
[ 0.          0.         22.61986495]

[0.0, 0.0, 0.1, 0.9]
[ 0.          0.         12.68038349]

[0.0, 0.0, 0.1, 1.0]
[ 0.          0.         11.42118627]

[0.0, 0.0, 0.5, 0.0]
[  0.   0. 180.]

[0.0, 0.0, 0.5, 0.1]
[  0.           0.         157.38013505]

[0.0, 0.0, 0.5, 0.5]
[ 0.  0. 90.]

[0.0, 0.0, 0.5, 0.9]
[ 0.         0.        58.1092082]

[0.0, 0.0, 0.5, 1.0]
[ 0.          0.         53.13010235]

[0.0, 0.0, 0.9, 0.0]
[  0.   0. 180.]

[0.0, 0.0, 0.9, 0.1]
[  0.           0.         167.31961651]

[0.0, 0.0, 0.9, 0.5]
[  0.          0.        121.8907918]

[0.0, 0.0, 0.9, 0.9]
[ 0.  0. 90.]

[0.0, 0.0, 0.9, 1.0]
[ 0.          0.         83.97442499]

[0.0, 0.0, 1.0, 0.0]
[  0.   0. 180.]

[0.0, 0.0, 1.0, 0.1]
[  0

In [11]:
q = np.quaternion(1,0,0,0)

In [31]:
q1 = np.quaternion(1,0,1,1)

In [32]:
q1.inverse()

quaternion(0.333333333333333, -0, -0.333333333333333, -0.333333333333333)

In [33]:
q2ea(q1)

IndexError: invalid index to scalar variable.

In [34]:
type(q)

quaternion

In [36]:
q.x

0.0